test deployment file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -187,6 +187,7 @@ jobs:
             - "*.zip"
             - "*.txt"
       - attach_workspace:
+          command: echo "Attaching workspace"
           at: workspace
       - store_artifacts:
           path: workspace/*.zip
@@ -200,10 +201,10 @@ jobs:
       - attach_workspace:
           at: ~/transcom/trdm-lambda/workspace
       - run: |
-          if [-f /workspace/deployment-package.stg.zip]; then
-            echo "deployment-package.stg.zip found"; exit 1
+          if [-f /workspace/deployment-packagetest.stg.zip]; then
+            echo "deployment-packagetest.stg.zip found"; exit 1
           else
-            echo "deployment-package.stg.zip not found"; exit 1
+            echo "deployment-packagetest.stg.zip not found"; exit 1
           fi
 # orbs:
 #   aws-s3: circleci/aws-s3@3.1.1 # use the AWS S3 orb
